// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogDocumentDataSlicesSlice = CtaSlice | HeroSlice | BlogPreviewCardSlice;

/**
 * Content for blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>; /**
   * Meta Title field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;

type ContentDocumentDataSlicesSlice =
  | CtaSlice
  | BlogPreviewCardSlice
  | BlogPostSlice
  | PartnersContentSlice
  | ContentSlice
  | HeroSlice;

/**
 * Content for content documents
 */
interface ContentDocumentData {
  /**
   * Slice Zone field in *content*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: content.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContentDocumentDataSlicesSlice>; /**
   * Meta Title field in *content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: content.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: content.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * content document from Prismic
 *
 * - **API ID**: `content`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContentDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContentDocumentData>,
    "content",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | ClientCarouselSlice
  | TestimonialsSlice
  | ContentSlice
  | PartnersCarouselSlice
  | FaqSlice
  | CtaSlice
  | MilestonesSlice
  | PropertiesSlice
  | RecentSlice
  | AboutSlice
  | HeroSlice;

/**
 * Content for home page documents
 */
interface HomePageDocumentData {
  /**
   * title field in *home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | PartnersContentSlice
  | PartnersCarouselSlice
  | RecentSlice
  | CtaSlice
  | FaqSlice
  | PropertiesSlice
  | MilestonesSlice
  | AboutSlice
  | HeroSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProjectsDocumentDataSlicesSlice =
  | TestimonialsSlice
  | ClientCarouselSlice
  | PropertiesSlice
  | HeroSlice;

/**
 * Content for projects documents
 */
interface ProjectsDocumentData {
  /**
   * Slice Zone field in *projects*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectsDocumentDataSlicesSlice>; /**
   * Meta Title field in *projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: projects.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: projects.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectsDocumentData>,
    "projects",
    Lang
  >;

type PropertiesDocumentDataSlicesSlice =
  | PartnerCardsSlice
  | CtaSlice
  | TestimonialsSlice
  | PartnersCarouselSlice
  | PropertiesSlice
  | HeroSlice;

/**
 * Content for properties documents
 */
interface PropertiesDocumentData {
  /**
   * Slice Zone field in *properties*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PropertiesDocumentDataSlicesSlice>; /**
   * Meta Title field in *properties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: properties.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *properties*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: properties.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *properties*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * properties document from Prismic
 *
 * - **API ID**: `properties`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PropertiesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PropertiesDocumentData>,
    "properties",
    Lang
  >;

/**
 * Item in *Settings → navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * link field in *Settings → navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * label field in *Settings → navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Settings → cta*
 */
export interface SettingsDocumentDataCtaItem {
  /**
   * cta link field in *Settings → cta*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * cta label field in *Settings → cta*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta[].cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;
}

/**
 * Item in *Settings → socials*
 */
export interface SettingsDocumentDataSocialsItem {
  /**
   * icons field in *Settings → socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].icons
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icons: prismic.ImageField<never>;

  /**
   * icon link field in *Settings → socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[].icon_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  icon_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Settings → legal*
 */
export interface SettingsDocumentDataLegaItem {
  /**
   * legal link field in *Settings → legal*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.lega[].legal_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  legal_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * legal label field in *Settings → legal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.lega[].legal_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  legal_label: prismic.KeyTextField;
}

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * site title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * meta description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * paragraph field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * og image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * cta field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cta[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta: prismic.GroupField<Simplify<SettingsDocumentDataCtaItem>>;

  /**
   * socials field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socials: prismic.GroupField<Simplify<SettingsDocumentDataSocialsItem>>;

  /**
   * legal field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.lega[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  lega: prismic.GroupField<Simplify<SettingsDocumentDataLegaItem>>;

  /**
   * `slices` field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | ContentDocument
  | HomePageDocument
  | PageDocument
  | ProjectsDocument
  | PropertiesDocument
  | SettingsDocument;

/**
 * Item in *About → Default → Primary → links*
 */
export interface AboutSliceDefaultPrimaryLinksItem {
  /**
   * link field in *About → Default → Primary → links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.links[].about
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  about: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * label field in *About → Default → Primary → links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *About → alternate → Primary → links*
 */
export interface AboutSliceAlternatePrimaryLinksItem {
  /**
   * link field in *About → alternate → Primary → links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.alternate.primary.links[].about
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  about: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * label field in *About → alternate → Primary → links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.alternate.primary.links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * caption field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * links field in *About → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<AboutSliceDefaultPrimaryLinksItem>>;

  /**
   * history field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.history
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  history: prismic.RichTextField;

  /**
   * about img field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  about_img: prismic.ImageField<never>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *About → alternate → Primary*
 */
export interface AboutSliceAlternatePrimary {
  /**
   * caption field in *About → alternate → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.alternate.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * links field in *About → alternate → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.alternate.primary.links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<AboutSliceAlternatePrimaryLinksItem>>;

  /**
   * about_img field in *About → alternate → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.alternate.primary.about_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  about_img: prismic.ImageField<never>;
}

/**
 * alternate variation for About Slice
 *
 * - **API ID**: `alternate`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceAlternate = prismic.SharedSliceVariation<
  "alternate",
  Simplify<AboutSliceAlternatePrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault | AboutSliceAlternate;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *BlogPost → Default → Primary → Button Group*
 */
export interface BlogPostSliceDefaultPrimaryButtonGroupItem {
  /**
   * Button link field in *BlogPost → Default → Primary → Button Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.button_group[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button label  field in *BlogPost → Default → Primary → Button Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.button_group[].button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Primary content in *BlogPost → Default → Primary*
 */
export interface BlogPostSliceDefaultPrimary {
  /**
   * Blog image  field in *BlogPost → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.blog_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  blog_image: prismic.ImageField<never>;

  /**
   * Blog heading  field in *BlogPost → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.blog_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  blog_heading: prismic.RichTextField;

  /**
   * Blog content  field in *BlogPost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.blog_content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blog_content: prismic.KeyTextField;

  /**
   * sub heading field in *BlogPost → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;

  /**
   * Sub heading content  field in *BlogPost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.sub_heading_content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sub_heading_content: prismic.KeyTextField;

  /**
   * Button Group field in *BlogPost → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.default.primary.button_group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  button_group: prismic.GroupField<
    Simplify<BlogPostSliceDefaultPrimaryButtonGroupItem>
  >;
}

/**
 * Default variation for BlogPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPostSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPost*
 */
type BlogPostSliceVariation = BlogPostSliceDefault;

/**
 * BlogPost Shared Slice
 *
 * - **API ID**: `blog_post`
 * - **Description**: BlogPost
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPostSlice = prismic.SharedSlice<
  "blog_post",
  BlogPostSliceVariation
>;

/**
 * Item in *BlogPreviewCard → Default → Primary → Blog Group*
 */
export interface BlogPreviewCardSliceDefaultPrimaryBlogGroupItem {
  /**
   * Blog image  field in *BlogPreviewCard → Default → Primary → Blog Group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview_card.default.primary.blog_group[].blog_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  blog_image: prismic.ImageField<never>;

  /**
   * Blog heading field in *BlogPreviewCard → Default → Primary → Blog Group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview_card.default.primary.blog_group[].blog_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  blog_heading: prismic.RichTextField;

  /**
   * Blog Caption field in *BlogPreviewCard → Default → Primary → Blog Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview_card.default.primary.blog_group[].blog_caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blog_caption: prismic.KeyTextField;

  /**
   * Blog text field in *BlogPreviewCard → Default → Primary → Blog Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview_card.default.primary.blog_group[].blog_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blog_text: prismic.KeyTextField;

  /**
   * Blog link field in *BlogPreviewCard → Default → Primary → Blog Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview_card.default.primary.blog_group[].blog_label
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  blog_label: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *BlogPreviewCard → Default → Primary*
 */
export interface BlogPreviewCardSliceDefaultPrimary {
  /**
   * Blog Group field in *BlogPreviewCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_preview_card.default.primary.blog_group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blog_group: prismic.GroupField<
    Simplify<BlogPreviewCardSliceDefaultPrimaryBlogGroupItem>
  >;
}

/**
 * Default variation for BlogPreviewCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPreviewCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogPreviewCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogPreviewCard*
 */
type BlogPreviewCardSliceVariation = BlogPreviewCardSliceDefault;

/**
 * BlogPreviewCard Shared Slice
 *
 * - **API ID**: `blog_preview_card`
 * - **Description**: BlogPreviewCard
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPreviewCardSlice = prismic.SharedSlice<
  "blog_preview_card",
  BlogPreviewCardSliceVariation
>;

/**
 * Item in *ClientCarousel → Default → Primary → client_button*
 */
export interface ClientCarouselSliceDefaultPrimaryClientButtonItem {
  /**
   * client_label field in *ClientCarousel → Default → Primary → client_button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client_carousel.default.primary.client_button[].client_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_label: prismic.KeyTextField;

  /**
   * client_link field in *ClientCarousel → Default → Primary → client_button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: client_carousel.default.primary.client_button[].client_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  client_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *ClientCarousel → Default → Primary → client_group*
 */
export interface ClientCarouselSliceDefaultPrimaryClientGroupItem {
  /**
   * client_img field in *ClientCarousel → Default → Primary → client_group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: client_carousel.default.primary.client_group[].client_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  client_img: prismic.ImageField<never>;

  /**
   * client_name  field in *ClientCarousel → Default → Primary → client_group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client_carousel.default.primary.client_group[].client_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  client_name: prismic.RichTextField;
}

/**
 * Primary content in *ClientCarousel → Default → Primary*
 */
export interface ClientCarouselSliceDefaultPrimary {
  /**
   * clients_heading field in *ClientCarousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client_carousel.default.primary.clients_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  clients_heading: prismic.KeyTextField;

  /**
   * client_paragraph field in *ClientCarousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client_carousel.default.primary.client_paragraph
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client_paragraph: prismic.KeyTextField;

  /**
   * client_button field in *ClientCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: client_carousel.default.primary.client_button[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  client_button: prismic.GroupField<
    Simplify<ClientCarouselSliceDefaultPrimaryClientButtonItem>
  >;

  /**
   * client_group field in *ClientCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: client_carousel.default.primary.client_group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  client_group: prismic.GroupField<
    Simplify<ClientCarouselSliceDefaultPrimaryClientGroupItem>
  >;
}

/**
 * Default variation for ClientCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ClientCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClientCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ClientCarousel*
 */
type ClientCarouselSliceVariation = ClientCarouselSliceDefault;

/**
 * ClientCarousel Shared Slice
 *
 * - **API ID**: `client_carousel`
 * - **Description**: ClientCarousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ClientCarouselSlice = prismic.SharedSlice<
  "client_carousel",
  ClientCarouselSliceVariation
>;

/**
 * Item in *Metrics → Default → Primary → overview*
 */
export interface ContentSliceDefaultPrimaryOverviewItem {
  /**
   * stat result field in *Metrics → Default → Primary → overview*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.overview[].stat_result
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_result: prismic.KeyTextField;

  /**
   * al stat field in *Metrics → Default → Primary → overview*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.overview[].al_stat
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  al_stat: prismic.KeyTextField;
}

/**
 * Item in *Metrics → Default → Primary → gallery img*
 */
export interface ContentSliceDefaultPrimaryGalleryImgItem {
  /**
   * gal img field in *Metrics → Default → Primary → gallery img*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.gallery_img[].gal_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gal_img: prismic.ImageField<never>;
}

/**
 * Primary content in *Metrics → Default → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * title field in *Metrics → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * geo field in *Metrics → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.geo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  geo: prismic.KeyTextField;

  /**
   * over paragraph field in *Metrics → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.over_paragraph
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  over_paragraph: prismic.KeyTextField;

  /**
   * overview field in *Metrics → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.overview[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  overview: prismic.GroupField<
    Simplify<ContentSliceDefaultPrimaryOverviewItem>
  >;

  /**
   * gallery img field in *Metrics → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.gallery_img[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery_img: prismic.GroupField<
    Simplify<ContentSliceDefaultPrimaryGalleryImgItem>
  >;
}

/**
 * Default variation for Metrics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Metrics*
 */
type ContentSliceVariation = ContentSliceDefault;

/**
 * Metrics Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSlice = prismic.SharedSlice<
  "content",
  ContentSliceVariation
>;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * cta img field in *Cta → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cta_img: prismic.ImageField<never>;

  /**
   * cta heading field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cta_heading: prismic.RichTextField;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Faq → Default → Primary → faq*
 */
export interface FaqSliceDefaultPrimaryQuestionItem {
  /**
   * question field in *Faq → Default → Primary → faq*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.question[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * answer field in *Faq → Default → Primary → faq*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.question[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * heading field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * sub heading field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;

  /**
   * paragraph field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * faq field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.question[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  question: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryQuestionItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Button Group*
 */
export interface HeroSliceDefaultPrimaryButtonGroupItem {
  /**
   * button label field in *Hero → Default → Primary → Button Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_group[].button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * button link field in *Hero → Default → Primary → Button Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_group[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Button Group field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  button_group: prismic.GroupField<
    Simplify<HeroSliceDefaultPrimaryButtonGroupItem>
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → alternate → Primary*
 */
export interface HeroSliceAlternatePrimary {
  /**
   * heading field in *Hero → alternate → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.alternate.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * body field in *Hero → alternate → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.alternate.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * image field in *Hero → alternate → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.alternate.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * alternate variation for Hero Slice
 *
 * - **API ID**: `alternate`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceAlternate = prismic.SharedSliceVariation<
  "alternate",
  Simplify<HeroSliceAlternatePrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceAlternate;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Milestones → Default → Primary*
 */
export interface MilestonesSliceDefaultPrimary {
  /**
   * port heading field in *Milestones → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestones.default.primary.port_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  port_heading: prismic.KeyTextField;

  /**
   * port sub heading field in *Milestones → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestones.default.primary.port_sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  port_sub_heading: prismic.KeyTextField;

  /**
   * port paragraph field in *Milestones → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestones.default.primary.port_paragraph
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  port_paragraph: prismic.KeyTextField;

  /**
   * heading field in *Milestones → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestones.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * sub heading field in *Milestones → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestones.default.primary.sub_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  sub_heading: prismic.RichTextField;

  /**
   * paragraph field in *Milestones → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestones.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for Milestones Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MilestonesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MilestonesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Milestones*
 */
type MilestonesSliceVariation = MilestonesSliceDefault;

/**
 * Milestones Shared Slice
 *
 * - **API ID**: `milestones`
 * - **Description**: Milestones
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MilestonesSlice = prismic.SharedSlice<
  "milestones",
  MilestonesSliceVariation
>;

/**
 * Item in *PartnerCards → Default → Primary → Partner Card*
 */
export interface PartnerCardsSliceDefaultPrimaryPartnerCardItem {
  /**
   * Partner Image field in *PartnerCards → Default → Primary → Partner Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_cards.default.primary.partner_card[].partner_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  partner_image: prismic.ImageField<never>;

  /**
   * Partner Heading field in *PartnerCards → Default → Primary → Partner Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_cards.default.primary.partner_card[].partner_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_heading: prismic.KeyTextField;

  /**
   * Partner Content  field in *PartnerCards → Default → Primary → Partner Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_cards.default.primary.partner_card[].partner_content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_content: prismic.KeyTextField;

  /**
   * Partner Link field in *PartnerCards → Default → Primary → Partner Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_cards.default.primary.partner_card[].partner_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  partner_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * partner_tag field in *PartnerCards → Default → Primary → Partner Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_cards.default.primary.partner_card[].partner_tag
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_tag: prismic.KeyTextField;
}

/**
 * Primary content in *PartnerCards → Default → Primary*
 */
export interface PartnerCardsSliceDefaultPrimary {
  /**
   * partner_hero field in *PartnerCards → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_cards.default.primary.partner_hero
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  partner_hero: prismic.ImageField<never>;

  /**
   * Partner_title field in *PartnerCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_cards.default.primary.partner_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_title: prismic.KeyTextField;

  /**
   * Partner Content  field in *PartnerCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_cards.default.primary.partner_content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_content: prismic.KeyTextField;

  /**
   * Partner Card field in *PartnerCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_cards.default.primary.partner_card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  partner_card: prismic.GroupField<
    Simplify<PartnerCardsSliceDefaultPrimaryPartnerCardItem>
  >;
}

/**
 * Default variation for PartnerCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnerCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnerCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PartnerCards*
 */
type PartnerCardsSliceVariation = PartnerCardsSliceDefault;

/**
 * PartnerCards Shared Slice
 *
 * - **API ID**: `partner_cards`
 * - **Description**: PartnerCards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnerCardsSlice = prismic.SharedSlice<
  "partner_cards",
  PartnerCardsSliceVariation
>;

/**
 * Item in *PartnersCarousel → Default → Primary → partners carousel*
 */
export interface PartnersCarouselSliceDefaultPrimaryPartnersCarouselItem {
  /**
   * partner_img field in *PartnersCarousel → Default → Primary → partners carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_carousel.default.primary.partners_carousel[].partner_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  partner_img: prismic.ImageField<never>;

  /**
   * partner_link field in *PartnersCarousel → Default → Primary → partners carousel*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_carousel.default.primary.partners_carousel[].partner_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  partner_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * partner_heading  field in *PartnersCarousel → Default → Primary → partners carousel*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: heading
   * - **API ID Path**: partners_carousel.default.primary.partners_carousel[].partner_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  partner_heading: prismic.RichTextField;
}

/**
 * Primary content in *PartnersCarousel → Default → Primary*
 */
export interface PartnersCarouselSliceDefaultPrimary {
  /**
   * partners carousel field in *PartnersCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_carousel.default.primary.partners_carousel[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  partners_carousel: prismic.GroupField<
    Simplify<PartnersCarouselSliceDefaultPrimaryPartnersCarouselItem>
  >;
}

/**
 * Default variation for PartnersCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PartnersCarousel*
 */
type PartnersCarouselSliceVariation = PartnersCarouselSliceDefault;

/**
 * PartnersCarousel Shared Slice
 *
 * - **API ID**: `partners_carousel`
 * - **Description**: PartnersCarousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersCarouselSlice = prismic.SharedSlice<
  "partners_carousel",
  PartnersCarouselSliceVariation
>;

/**
 * Item in *PartnersContent → Default → Primary → Button*
 */
export interface PartnersContentSliceDefaultPrimaryButtonItem {
  /**
   * Button Label field in *PartnersContent → Default → Primary → Button*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.button[].button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *PartnersContent → Default → Primary → Button*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.button[].button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *PartnersContent → Default → Primary → Partner Variant Content*
 */
export interface PartnersContentSliceDefaultPrimaryPartnerVariantContentItem {
  /**
   * Variant Image field in *PartnersContent → Default → Primary → Partner Variant Content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_variant_content[].variant_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  variant_image: prismic.ImageField<never>;

  /**
   * Variant Heading  field in *PartnersContent → Default → Primary → Partner Variant Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_variant_content[].variant_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  variant_heading: prismic.KeyTextField;

  /**
   * Variant Content  field in *PartnersContent → Default → Primary → Partner Variant Content*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_variant_content[].variant_content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  variant_content: prismic.KeyTextField;
}

/**
 * Item in *PartnersContent → Default → Primary → Partner_Content *
 */
export interface PartnersContentSliceDefaultPrimaryPartnerContentItem {
  /**
   * Partner Image field in *PartnersContent → Default → Primary → Partner_Content *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_content[].partner_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  partner_image: prismic.ImageField<never>;

  /**
   * Partner Heading field in *PartnersContent → Default → Primary → Partner_Content *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_content[].partner_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_heading: prismic.KeyTextField;

  /**
   * Partner Content  field in *PartnersContent → Default → Primary → Partner_Content *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_content[].partner_content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_content: prismic.KeyTextField;

  /**
   * Partner Link field in *PartnersContent → Default → Primary → Partner_Content *
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_content[].partner_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  partner_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Partner Label field in *PartnersContent → Default → Primary → Partner_Content *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_content[].partner_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partner_label: prismic.KeyTextField;
}

/**
 * Primary content in *PartnersContent → Default → Primary*
 */
export interface PartnersContentSliceDefaultPrimary {
  /**
   * partner_img  field in *PartnersContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  partner_img: prismic.ImageField<never>;

  /**
   * title field in *PartnersContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * content  field in *PartnersContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  content: prismic.KeyTextField;

  /**
   * Button field in *PartnersContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.button[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  button: prismic.GroupField<
    Simplify<PartnersContentSliceDefaultPrimaryButtonItem>
  >;

  /**
   * Reason_Caption field in *PartnersContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.reason_caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  reason_caption: prismic.KeyTextField;

  /**
   * Partner Variant Content field in *PartnersContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_variant_content[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  partner_variant_content: prismic.GroupField<
    Simplify<PartnersContentSliceDefaultPrimaryPartnerVariantContentItem>
  >;

  /**
   * Partner_Content  field in *PartnersContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_content.default.primary.partner_content[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  partner_content: prismic.GroupField<
    Simplify<PartnersContentSliceDefaultPrimaryPartnerContentItem>
  >;
}

/**
 * Default variation for PartnersContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PartnersContent*
 */
type PartnersContentSliceVariation = PartnersContentSliceDefault;

/**
 * PartnersContent Shared Slice
 *
 * - **API ID**: `partners_content`
 * - **Description**: PartnersContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersContentSlice = prismic.SharedSlice<
  "partners_content",
  PartnersContentSliceVariation
>;

/**
 * Item in *Properties → default → Primary → image navigator*
 */
export interface PropertiesSliceAlternatePrimaryImageNavigatorItem {
  /**
   * navigator link field in *Properties → default → Primary → image navigator*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.alternate.primary.image_navigator[].navigator_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigator_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * display img field in *Properties → default → Primary → image navigator*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.alternate.primary.image_navigator[].display_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  display_img: prismic.ImageField<never>;

  /**
   * heading field in *Properties → default → Primary → image navigator*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.alternate.primary.image_navigator[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * paragraph field in *Properties → default → Primary → image navigator*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.alternate.primary.image_navigator[].paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;
}

/**
 * Primary content in *Properties → default → Primary*
 */
export interface PropertiesSliceAlternatePrimary {
  /**
   * heading field in *Properties → default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.alternate.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * paragraph field in *Properties → default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.alternate.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * image navigator field in *Properties → default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: properties.alternate.primary.image_navigator[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  image_navigator: prismic.GroupField<
    Simplify<PropertiesSliceAlternatePrimaryImageNavigatorItem>
  >;
}

/**
 * default variation for Properties Slice
 *
 * - **API ID**: `alternate`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PropertiesSliceAlternate = prismic.SharedSliceVariation<
  "alternate",
  Simplify<PropertiesSliceAlternatePrimary>,
  never
>;

/**
 * Slice variation for *Properties*
 */
type PropertiesSliceVariation = PropertiesSliceAlternate;

/**
 * Properties Shared Slice
 *
 * - **API ID**: `properties`
 * - **Description**: Properties
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PropertiesSlice = prismic.SharedSlice<
  "properties",
  PropertiesSliceVariation
>;

/**
 * Item in *Projects → Default → Primary → navigator*
 */
export interface RecentSliceDefaultPrimaryNavigatorItem {
  /**
   * link field in *Projects → Default → Primary → navigator*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.navigator[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * label field in *Projects → Default → Primary → navigator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.navigator[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Projects → Default → Primary → image navigator*
 */
export interface RecentSliceDefaultPrimaryImageNavigatorItem {
  /**
   * display img field in *Projects → Default → Primary → image navigator*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.image_navigator[].display_img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  display_img: prismic.ImageField<never>;

  /**
   * display link field in *Projects → Default → Primary → image navigator*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.image_navigator[].display_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  display_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * display text field in *Projects → Default → Primary → image navigator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.image_navigator[].display_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  display_text: prismic.KeyTextField;

  /**
   * display geo field in *Projects → Default → Primary → image navigator*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.image_navigator[].display_geo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  display_geo: prismic.KeyTextField;
}

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface RecentSliceDefaultPrimary {
  /**
   * heading field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * paragraph field in *Projects → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  paragraph: prismic.RichTextField;

  /**
   * navigator field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.navigator[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigator: prismic.GroupField<
    Simplify<RecentSliceDefaultPrimaryNavigatorItem>
  >;

  /**
   * image navigator field in *Projects → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: recent.default.primary.image_navigator[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  image_navigator: prismic.GroupField<
    Simplify<RecentSliceDefaultPrimaryImageNavigatorItem>
  >;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RecentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RecentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Projects*
 */
type RecentSliceVariation = RecentSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `recent`
 * - **Description**: Recent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RecentSlice = prismic.SharedSlice<"recent", RecentSliceVariation>;

/**
 * Item in *Testimonials → Default → Primary → Testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * testimonial image field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].testimonial_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  testimonial_image: prismic.ImageField<never>;

  /**
   * Heading  field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * paragraph field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].paragraph
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Testimonials field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      ContentDocument,
      ContentDocumentData,
      ContentDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataSlicesSlice,
      PropertiesDocument,
      PropertiesDocumentData,
      PropertiesDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataCtaItem,
      SettingsDocumentDataSocialsItem,
      SettingsDocumentDataLegaItem,
      SettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimaryLinksItem,
      AboutSliceDefaultPrimary,
      AboutSliceAlternatePrimaryLinksItem,
      AboutSliceAlternatePrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      AboutSliceAlternate,
      BlogPostSlice,
      BlogPostSliceDefaultPrimaryButtonGroupItem,
      BlogPostSliceDefaultPrimary,
      BlogPostSliceVariation,
      BlogPostSliceDefault,
      BlogPreviewCardSlice,
      BlogPreviewCardSliceDefaultPrimaryBlogGroupItem,
      BlogPreviewCardSliceDefaultPrimary,
      BlogPreviewCardSliceVariation,
      BlogPreviewCardSliceDefault,
      ClientCarouselSlice,
      ClientCarouselSliceDefaultPrimaryClientButtonItem,
      ClientCarouselSliceDefaultPrimaryClientGroupItem,
      ClientCarouselSliceDefaultPrimary,
      ClientCarouselSliceVariation,
      ClientCarouselSliceDefault,
      ContentSlice,
      ContentSliceDefaultPrimaryOverviewItem,
      ContentSliceDefaultPrimaryGalleryImgItem,
      ContentSliceDefaultPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimaryQuestionItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonGroupItem,
      HeroSliceDefaultPrimary,
      HeroSliceAlternatePrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceAlternate,
      MilestonesSlice,
      MilestonesSliceDefaultPrimary,
      MilestonesSliceVariation,
      MilestonesSliceDefault,
      PartnerCardsSlice,
      PartnerCardsSliceDefaultPrimaryPartnerCardItem,
      PartnerCardsSliceDefaultPrimary,
      PartnerCardsSliceVariation,
      PartnerCardsSliceDefault,
      PartnersCarouselSlice,
      PartnersCarouselSliceDefaultPrimaryPartnersCarouselItem,
      PartnersCarouselSliceDefaultPrimary,
      PartnersCarouselSliceVariation,
      PartnersCarouselSliceDefault,
      PartnersContentSlice,
      PartnersContentSliceDefaultPrimaryButtonItem,
      PartnersContentSliceDefaultPrimaryPartnerVariantContentItem,
      PartnersContentSliceDefaultPrimaryPartnerContentItem,
      PartnersContentSliceDefaultPrimary,
      PartnersContentSliceVariation,
      PartnersContentSliceDefault,
      PropertiesSlice,
      PropertiesSliceAlternatePrimaryImageNavigatorItem,
      PropertiesSliceAlternatePrimary,
      PropertiesSliceVariation,
      PropertiesSliceAlternate,
      RecentSlice,
      RecentSliceDefaultPrimaryNavigatorItem,
      RecentSliceDefaultPrimaryImageNavigatorItem,
      RecentSliceDefaultPrimary,
      RecentSliceVariation,
      RecentSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
