// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  blog_post: dynamic(() => import("./BlogPost")),
  blog_preview_card: dynamic(() => import("./BlogPreviewCard")),
  client_carousel: dynamic(() => import("./ClientCarousel")),
  content: dynamic(() => import("./Metrics")),
  cta: dynamic(() => import("./Cta")),
  faq: dynamic(() => import("./Faq")),
  hero: dynamic(() => import("./Hero")),
  milestones: dynamic(() => import("./Milestones")),
  partner_cards: dynamic(() => import("./PartnerCards")),
  partners_carousel: dynamic(() => import("./PartnersCarousel")),
  partners_content: dynamic(() => import("./PartnersContent")),
  properties: dynamic(() => import("./Properties")),
  recent: dynamic(() => import("./Projects")),
  testimonials: dynamic(() => import("./Testimonials")),
};
